# Generated by Django 5.2.7 on 2025-10-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyprofile',
            name='google_maps_link',
            field=models.URLField(blank=True, verbose_name='Enlace de Google Maps'),
        ),
    ]
