# Generated by Django 5.2.7 on 2025-10-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_type', models.CharField(choices=[('internal', 'Entrega Interna'), ('external', 'Entrega Externa'), ('pickup', 'Recoger en Farmacia')], max_length=20, verbose_name='Tipo de Entrega')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('assigned', 'Asignado'), ('picked_up', 'Recogido'), ('in_transit', 'En Tránsito'), ('delivered', 'Entregado'), ('failed', 'Fallido')], default='pending', max_length=20, verbose_name='Estado')),
                ('external_service', models.CharField(blank=True, choices=[('riddy', 'Riddy'), ('yummy', 'Yummy'), ('django_delivery', 'Django Delivery')], max_length=50, verbose_name='Servicio Externo')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='Número de Seguimiento')),
                ('estimated_delivery_time', models.DateTimeField(blank=True, null=True, verbose_name='Tiempo Estimado de Entrega')),
                ('delivery_person_name', models.CharField(blank=True, max_length=100, verbose_name='Nombre del Repartidor')),
                ('delivery_person_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono del Repartidor')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Asignado el')),
                ('picked_up_at', models.DateTimeField(blank=True, null=True, verbose_name='Recogido el')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Entregado el')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='Número de Orden')),
                ('order_status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('confirmed', 'Confirmado'), ('preparing', 'Preparando'), ('ready_for_delivery', 'Listo para Entrega'), ('in_delivery', 'En Entrega'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado de la Orden')),
                ('payment_status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido'), ('refunded', 'Reembolsado')], default='pending', max_length=20, verbose_name='Estado del Pago')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Impuestos')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo de Entrega')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('delivery_type', models.CharField(choices=[('internal', 'Entrega Interna'), ('external', 'Entrega Externa'), ('pickup', 'Recoger en Farmacia')], max_length=20, verbose_name='Tipo de Entrega')),
                ('delivery_address', models.TextField(blank=True, verbose_name='Dirección de Entrega')),
                ('delivery_instructions', models.TextField(blank=True, verbose_name='Instrucciones de Entrega')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('payment_deadline', models.DateTimeField(verbose_name='Fecha Límite de Pago')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Entregado el')),
                ('client_notes', models.TextField(blank=True, verbose_name='Notas del Cliente')),
                ('pharmacy_notes', models.TextField(blank=True, verbose_name='Notas de la Farmacia')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Órdenes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Total')),
                ('prescription_image', models.ImageField(blank=True, null=True, upload_to='prescriptions/', verbose_name='Imagen de Receta')),
            ],
            options={
                'verbose_name': 'Artículo de Orden',
                'verbose_name_plural': 'Artículos de Órdenes',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('c2p', 'Pago Móvil C2P'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('bank_transfer', 'Transferencia Bancaria')], max_length=20, verbose_name='Método de Pago')),
                ('c2p_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono C2P')),
                ('c2p_reference', models.CharField(blank=True, max_length=100, verbose_name='Referencia C2P')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('currency', models.CharField(default='VES', max_length=3, verbose_name='Moneda')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='ID de Transacción')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('is_successful', models.BooleanField(default=False, verbose_name='Pago Exitoso')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Calificación')),
                ('comment', models.TextField(blank=True, verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
                'ordering': ['-created_at'],
            },
        ),
    ]
