# Generated by Django 5.2.7 on 2025-10-29 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_delivery_fee_alter_order_subtotal_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_order_number', models.CharField(max_length=20, unique=True, verbose_name='Número de Orden Maestra')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Total (USD)')),
                ('payment_status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido'), ('refunded', 'Reembolsado')], default='pending', max_length=20, verbose_name='Estado del Pago')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_orders', to='users.clientprofile', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Orden Maestra',
                'verbose_name_plural': 'Órdenes Maestras',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='master_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_orders', to='orders.masterorder', verbose_name='Orden Maestra'),
        ),
    ]
