# Generated by Django 5.2.7 on 2025-10-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_available',
            new_name='_is_available',
        ),
        migrations.AlterField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Original (USD)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio (USD)'),
        ),
    ]
